# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b7fa8a7b-e5f6-45ed-94df-9713518d8703";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd:1"
      "lazytime"
      "discard=async"
      "autodefrag"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/b7fa8a7b-e5f6-45ed-94df-9713518d8703";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd:1"
      "lazytime"
      "discard=async"
      "autodefrag"
    ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/b7fa8a7b-e5f6-45ed-94df-9713518d8703";
    fsType = "btrfs";
    options = [
      "subvol=@var"
      "compress=zstd:1"
      "lazytime"
      "discard=async"
      "autodefrag"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/b7fa8a7b-e5f6-45ed-94df-9713518d8703";
    fsType = "btrfs";
    options = [
      "subvol=@log"
      "compress=zstd:1"
      "lazytime"
      "discard=async"
      "autodefrag"
    ];
  };

  fileSystems."/root" = {
    device = "/dev/disk/by-uuid/b7fa8a7b-e5f6-45ed-94df-9713518d8703";
    fsType = "btrfs";
    options = [
      "subvol=@root"
      "compress=zstd:1"
      "lazytime"
      "discard=async"
      "autodefrag"
    ];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/1FBE-A31F";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/4a6d9f75-32af-4249-9376-0c279a4b050f"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
